-- CREANDO LA BASE DE DATOS
CREATE DATABASE crudnodejsmysql;

-- UTILIZANDO LA BASE DE DATOS
USE crudnodejsmysql;

-- CREANDO TABLAS
CREATE TABLE customer (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    direccion VARCHAR(100) NOT NULL,
    telefono VARCHAR(15) 
);

--PARA MOSTRAR TABLAS;
SHOW TABLES;

-- MOSTRAR ESTRUCTURA DE LAS TABLAS
DESCRIBE CUSTOMER; 